# Generated by Django 4.2.7 on 2023-11-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_chave_situacao_alter_chave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
