# Generated by Django 4.2.7 on 2023-11-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chave',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
